### ISSUE TITLE
在Android12上的疑问。

### ISSUE THREAD

**Issue by lcj0304** [Knight-ZXW/SpWaitKiller#7]
Android12源码：
```
      synchronized (sProcessingWork) {
            LinkedList<Runnable> work;

            synchronized (sLock) {
                work = sWork;
                sWork = new LinkedList<>();

                // Remove all msg-s as all work will be processed now
                getHandler().removeMessages(QueuedWorkHandler.MSG_RUN);
            }
            // 在work.size之前，如果其他线程又有数据向添加sWork ，Android12 work.size()重新设置代理，
            是不是添加到的sWork数据会丢失？work.size()可不在sLock下执行。

            if (work.size() > 0) {
                for (Runnable w : work) {
                    w.run();
                }

                if (DEBUG) {
                    Log.d(LOG_TAG, "processing " + work.size() + " items took " +
                            +(System.currentTimeMillis() - startTime) + " ms");
                }
            }
        }
```

**Comment by lcj0304** [comment]
另外，Android12上有崩溃的情况。
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
       at java.util.LinkedList$ListItr.next(LinkedList.java:892)
       at android.app.QueuedWork.processPendingWork(QueuedWork.java:264)
       at android.app.QueuedWork.access$000(QueuedWork.java:51)
       at android.app.QueuedWork$QueuedWorkHandler.handleMessage(QueuedWork.java:285)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by Knight-ZXW** [comment]
> 
 // 在work.size之前，如果其他线程又有数据向添加sWork ，Android12 work.size()重新设置代理，
            是不是添加到的sWork数据会丢失？work.size()可不在sLock下执行。

看了下代码， 此时 新的任务是添加到新的 sWork中，和被代理 size()函数的不是同一个对象。

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
       at java.util.LinkedList$ListItr.next(LinkedList.java:892)
       at android.app.QueuedWork.processPendingWork(QueuedWork.java:264)
       at android.app.QueuedWork.access$000(QueuedWork.java:51)
       at android.app.QueuedWork$QueuedWorkHandler.handleMessage(QueuedWork.java:285)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.os.HandlerThread.run(HandlerThread.java:67)

这个异常对应的264行，理论上Android 12 此时 size()函数总是返回0, 应该不会进入 下面的 迭代器执行， 你这个崩溃出现概率高吗，是在线上环境收集的异常吗？
![image](https://user-images.githubusercontent.com/11730925/188439988-a152cb8f-879c-4eaa-aa1a-f7166f9eb589.png)

**Comment by Knight-ZXW** [comment]
> 
 // 在work.size之前，如果其他线程又有数据向添加sWork ，Android12 work.size()重新设置代理，
            是不是添加到的sWork数据会丢失？work.size()可不在sLock下执行。

看了下代码， 此时 新的任务是添加到新的 sWork中，和被代理 size()函数的不是同一个对象。

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
       at java.util.LinkedList$ListItr.next(LinkedList.java:892)
       at android.app.QueuedWork.processPendingWork(QueuedWork.java:264)
       at android.app.QueuedWork.access$000(QueuedWork.java:51)
       at android.app.QueuedWork$QueuedWorkHandler.handleMessage(QueuedWork.java:285)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.os.HandlerThread.run(HandlerThread.java:67)

这个异常对应的264行，理论上Android 12 此时 size()函数总是返回0, 应该不会进入 下面的 迭代器执行， 你这个崩溃出现概率高吗，是在线上环境收集的异常吗？
![image](https://user-images.githubusercontent.com/11730925/188439988-a152cb8f-879c-4eaa-aa1a-f7166f9eb589.png)

**Comment by lcj0304** [comment]
> 我是有一个疑问和一个崩溃，崩溃和疑问没有关系。

先回复崩溃：
崩溃是线上环境，崩溃概率并不高。偶尔会有，我也看了代码，按道理不应该进入下面的循环。我本地无法重现。会不会出现某些字段代码失败导致的，我的崩溃信息也就上面给的这些。


关于疑问：

” 此时 新的任务是添加到新的 sWork中，和被代理 size()函数的不是同一个对象“
任务是添加到新的sWork中，但下面 work.size()时候，会重新使用代理对象去设置那个sWork字段，那此时加入新 的sWork的任务是不是就没机会处理了，整个对象都被替换掉了？

**Comment by Knight-ZXW** [comment]
> 

好像确实是有问题，Android 12重新设置 sWork字段的时候，应该重新代理下 目前的 sWork列表， 我验证一下这个问题

**Comment by Knight-ZXW** [comment]
> 
https://github.com/Knight-ZXW/SpWaitKiller/pull/8

@lcj0304   review下，这个BUG 和你的疑问 可能是同一个问题导致的，在Android12 每次调用 .size()函数后，此时sWork指向了一个新的对象， 应该重新 获取sWork的引用对象，重新进行代理
